name: 'Test and deploy'
on:
  push:
    branches: ['master']
  pull_request:
  workflow_dispatch:
jobs:
  test:
    name: 'Test'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Check out'
        uses: 'actions/checkout@v3'
      - name: 'Set up Go'
        uses: 'actions/setup-go@v3'
        with:
          go-version: '1.18'
      - name: 'Cache Go dependencies'
        uses: 'actions/cache@v3'
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: "${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}"
      - name: 'Set up Node.js'
        uses: 'actions/setup-node@v3'
        with:
          cache: 'npm'
      - name: 'Test'
        run: 'script/test'
  deploy:
    name: 'Deploy'
    needs: 'test'
    if: "github.event_name != 'pull_request'"
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Check out'
        uses: 'actions/checkout@v3'
      - name: 'Set up Go'
        uses: 'actions/setup-go@v3'
        with:
          go-version: '1.18'
      - name: 'Cache Go dependencies'
        uses: 'actions/cache@v3'
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: "${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}"
      - name: 'Build'
        run: 'script/build -env prod'
      - name: 'Deploy'
        uses: 'peaceiris/actions-gh-pages@v3.8.0'
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          publish_dir: './build'
          cname: 'astrophena.name'
