name: 'Deploy'
on:
  workflow_run:
    workflows: ['Test']
    types: ['completed']
    branches: ['master']
jobs:
  deploy:
    name: 'Deploy'
    runs-on: 'ubuntu-latest'
    if: |
      ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: 'Check out'
        uses: 'actions/checkout@v3'
      - name: 'Set up Go'
        uses: 'actions/setup-go@v3'
        with:
          go-version: '1.18'
      - name: 'Cache Go dependencies'
        uses: 'actions/cache@v3'
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: |
            ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      - name: 'Build'
        run: './build.go -env prod'
      - name: 'Deploy'
        uses: 'peaceiris/actions-gh-pages@v3.8.0'
        with:
          github_token: |
            ${{ secrets.GITHUB_TOKEN }}
          publish_dir: './build'
          cname: 'astrophena.name'
