name: 'Deploy'
on:
  push:
    branches: ['master']
jobs:
  deploy:
    name: 'Deploy'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Check out'
        uses: 'actions/checkout@v2.4.0'
      - name: 'Set up Go'
        uses: 'actions/setup-go@v2.1.5'
        with:
          go-version: '1.17'
      - name: 'Cache dependencies and build cache'
        uses: 'actions/cache@v2.1.7'
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      - name: 'Run tests'
        run: 'go test'
      - name: 'Build'
        run: './build.go -env prod'
      - name: 'Deploy'
        uses: 'peaceiris/actions-gh-pages@v3'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: './build'
          cname: 'astrophena.name'
